import 'Movie.dart'; // Assuming Movie is imported correctly

class FavoriteMovie {
  final int idFavoriteMovie;
  final int idMovie;
  final String movieTitle;
  final String movieReleaseDate;
  final String movieCategory;
  final List<String> movieGenre;
  final String movieRating;
  final String imageCover;
  final List<String> availableDownloadLinks;

  FavoriteMovie({
    required this.idFavoriteMovie,
    required this.idMovie,
    required this.movieTitle,
    required this.movieReleaseDate,
    required this.movieCategory,
    required this.movieGenre,
    required this.movieRating,
    required this.imageCover,
    required this.availableDownloadLinks,
  });

  factory FavoriteMovie.fromJson(Map<String, dynamic> json) {
    return FavoriteMovie(
      idFavoriteMovie: json['idFavoriteMovie'],
      idMovie: json['idMovie'],
      movieTitle: json['movieTitle'],
      movieReleaseDate: json['movieReleaseDate'],
      movieCategory: json['movieCategory'],
      movieGenre: List<String>.from(json['movieGenre']),
      movieRating: json['movieRating'],
      imageCover: json['imageCover'],
      availableDownloadLinks: List<String>.from(json['availableDownloadLinks']),
    );
  }

  factory FavoriteMovie.fromMovie(Movie movie) {
    return FavoriteMovie(
      idFavoriteMovie: 0, // This might be generated by the backend
      idMovie: movie.id,
      movieTitle: movie.title,
      movieReleaseDate: movie.year.toString(),
      movieCategory: movie.genres.isNotEmpty ? movie.genres[0] : 'Unknown',
      movieGenre: movie.genres,
      movieRating: movie.rating.toString(),
      imageCover: movie.coverImage,
      availableDownloadLinks: movie.torrents.map((torrent) => torrent.url).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'idFavoriteMovie': idFavoriteMovie,
      'idMovie': idMovie,
      'movieTitle': movieTitle,
      'movieReleaseDate': movieReleaseDate,
      'movieCategory': movieCategory,
      'movieGenre': movieGenre,
      'movieRating': movieRating,
      'imageCover': imageCover,
      'availableDownloadLinks': availableDownloadLinks,
    };
  }
}
